apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
  namespace: chatapp-prod
  labels:
    app: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      # Your existing service account with Pod Identity
      serviceAccountName: chatapp-sa
      
      containers:
      - name: my-app
        image: amazon/aws-cli:latest
        ports:
        - containerPort: 80
        
        # Mount the secret as a file
        volumeMounts:
        - name: secrets-store
          mountPath: "/mnt/secrets"
          readOnly: true
        
        # Use secret as environment variable
        env:
        - name: APP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-app-k8s-secret
              key: password
        
        # Verify secrets are loaded
        command:
        - /bin/sh
        - -c
        - |
          sleep 3600
      
      volumes:
      - name: secrets-store
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "aws-secrets-provider"
