{{- if .Values.secrets.enabled }}
# =========================================
# Backend Application Secrets
# =========================================
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-backend-secret"
  namespace: {{ .Release.Namespace }}
  labels:
    app: backend
    component: backend-api
    {{- include "connecthub.labels" . | nindent 4 }}

type: Opaque

stringData:
  DB_PASSWORD: {{ .Values.secrets.dbPassword | quote }}
  SECRET_KEY: {{ .Values.secrets.secretKey | quote }}
  RABBITMQ_PASSWORD: {{ .Values.secrets.rabbitmqPassword | quote }}

{{- end }}

---
{{- if .Values.secrets.dockerhub.enabled }}
# =========================================
# Docker Hub Registry Secret
# =========================================
apiVersion: v1
kind: Secret
metadata:
  # Name must match imagePullSecrets in Deployment
  name: {{ .Values.secrets.dockerhub.secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "connecthub.labels" . | nindent 4 }}

# SPECIAL TYPE for Docker registry authentication
type: kubernetes.io/dockerconfigjson

data:
  .dockerconfigjson: {{ .Values.secrets.dockerhub.config | quote }}

{{- end }}
